### ISSUE TITLE
Build status: failing

### ISSUE THREAD

**Issue by ronkorving** [3rd-Eden/jackpot#3]
Are you aware that the tests currently do not pass?

**Comment by 3rd-Eden** [comment]
Im guessing the are failing because it takes my moatests branch in to account. Master branch is fine as i know.

**Comment by 3rd-Eden** [comment]
Just as I suspected 5f3e76f97a794ecc7ac2a65facf2a664cda940a6 fixed it and shows it as passing. But thanks for notifying me about it anyways!

**Comment by ronkorving** [comment]
Okay, cool :)
