### ISSUE TITLE
Reason for ms module

### ISSUE THREAD

**Issue by ianshward** [3rd-Eden/jackpot#8]
@3rd-Eden what is the reason for using the "ms" module?  I am going to work on https://github.com/3rd-Eden/node-memcached/issues/126 but see all settings there use numbers, whereas the settings for jackpot's retry, if specified as numbers, will be converted to strings.

**Comment by 3rd-Eden** [comment]
I always found that reading `10 seconds` is easier to understand then seeing `10000` or `1e4`. That's basically the only reason why I use that module. But it's not forcing you to use strings that are converted to numbers. So you can still do:

``` js
var pool = new Jackpot(100, { min: 10000, max: 100000 });
```

Which would be the same as:

``` js
var pool = new Jackpot(100, { min: '10 seconds', max: '100 seconds' });
```

**Comment by ianshward** [comment]
@3rd-Eden it appears that `ms` will turn `60000` into the string `'1m'`, which the retry module cannot handle.  W/ the first example you provide, if I console.log the `operation` var in jackpot, I get:

``` plain
{ _timeouts: [ NaN, NaN, NaN, NaN, NaN ],
  _fn: null,
  _errors: [],
  _attempts: 1,
  _operationTimeout: null,
  _operationTimeoutCb: null,
  _timeout: null }
```

versus your second example:

``` plain
{ _timeouts: [ 19898, 35112, 100000, 100000, 100000 ],
  _fn: null,
  _errors: [],
  _attempts: 1,
  _operationTimeout: null,
  _operationTimeoutCb: null,
  _timeout: null }
```

**Comment by 3rd-Eden** [comment]
There we go, I didn't test case. Thanks for catching it. Fixed ms and added a test against it.
